language: python
python:
        - "2.7"
# command to install dependencies
install:
        - pip install cython
        - pip install matplotlib
        - pip install pyvtk
        - pip install Mayavi[app]

before_script:
        - bash bin/install.sh
        # libfftw in ubuntu 12.04 is a bit older for fidimag.
        #- sudo apt-get install libsundials-serial-dev libfftw3-dev
        - make build
        - export PYTHONPATH="/home/travis/build/fangohr/fidimag:$PYTHONPATH"
        - export LD_LIBRARY_PATH="/home/travis/build/fangohr/fidimag/local/lib:$LD_LIBRARY_PATH"
        - export LD_RUN_PATH="/home/travis/build/fangohr/fidimag/local/lib:$LD_RUN_PATH"

# command to run tests
script:
        - make test-without-run-oommf
