language: python
python:
        - "2.7"
# command to install dependencies
install: 
        "pip install cython"

before_script:
        - bash bin/install.sh
        - make build
        - export PYTHONPATH="$HOME/fidimag:$PYTHONPATH"
# command to run tests
script: 
        - make test
