language: python
python:
        - "3.5"
        - "3.4"
        - "2.7"
# command to install dependencies
before_install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - sudo apt-get -qq update
  - sudo apt-get -qq install xvfb  # virtual X display for tests that need a display

install:
  - conda create -q -y -n fidimag-test python=$TRAVIS_PYTHON_VERSION cython matplotlib pytest scipy
  - source activate fidimag-test
  - pip install pyvtk six
  # Download and compile FFTW & Sundials locally
  - bash bin/install.sh

before_script:
        - make build
        - export PYTHONPATH="$TRAVIS_BUILD_DIR:$PYTHONPATH"
        - export LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/local/lib:$LD_LIBRARY_PATH"
        - export LD_RUN_PATH="$TRAVIS_BUILD_DIR/local/lib:$LD_RUN_PATH"
        - export OMP_NUM_THREADS=1
        - export MPLBACKEND=Agg
        # Tells matplotlib (?) to use PyQt class v2 APIs (I think)
        - export QT_API=pyqt

# command to run tests
# tvtk can't be imported without an X server, so we run in xvfb, which creates a virtual display
script:
  - xvfb-run --server-args="-screen 0 1024x768x24" make test-without-run-oommf


notifications:
  email:
    on_failure: always
