language: python
python:
        - "2.7"
# command to install dependencies
#install: 
#        "pip install matplotlib"

# Solve the matplotlib DISPLAY error when trying
# to use a headless machine
before_install:
        - bash bin/install.sh
        - make build
        - export PYTHONPATH="$HOME/fidimag:$PYTHONPATH"
# command to run tests
script: 
        - make test
